CREATE TABLE user
(
    USERNAME VARCHAR(128) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL
);
DROP TABLE IF EXISTS `user_role`;

CREATE TABLE `user_role`
(
    USER_ROLE_ID INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ROLE VARCHAR(45),
    USERNAME VARCHAR(128)
);
ALTER TABLE user_role ADD FOREIGN KEY (USERNAME) REFERENCES user (USERNAME) ON DELETE CASCADE;
CREATE INDEX USER_FK_idx ON user_role (USERNAME);
